### PR TITLE
Add "responseType"

### PR DESCRIPTION
**Pull request by mixa3607**
Add responseType. Requried for non default options.
After changes blob/arraybuffer/... responses works.

https://www.tampermonkey.net/documentation.php#GM_xmlhttpRequest
https://wiki.greasespot.net/GM.xmlHttpRequest

### CODE REVIEW

**Comment by Trim21** [comment]
There is already a type definitions for UserScript I think? https://www.npmjs.com/package/@types/gm

**Comment by mixa3607** [comment]
Are these types for imagemagick or am I misunderstanding something?

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/gm/index.d.ts
https://github.com/aheckmann/gm#readme

**Comment by Trim21** [comment]
sorry, it's https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/greasemonkey

**Comment by mixa3607** [comment]
I checked this package before add d.ts to current project. `@types/greasemonkey` not contain `responseType` but in official docs it presented

**Pull request merged**
